name: setup-helm-plugins
description: Install pinned Helm plugins (diff, secrets, s3)
inputs:
  helm_binary:
    description: Path to helm binary
    required: false
    default: helm
  diff_version:
    required: false
    default: "v3.9.7"
  secrets_version:
    required: false
    default: "v4.6.0"
  s3_version:
    required: false
    default: "v0.17.0"
  uninstall_first:
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Helm v3.12.1
      shell: bash
      run: |
        set -euo pipefail
        curl -L https://get.helm.sh/helm-v3.12.1-linux-amd64.tar.gz -o helm.tgz
        tar xzf helm.tgz
        sudo mv linux-amd64/helm /usr/local/bin/helm
        helm version

    - name: Install helmfile v0.155.0
      shell: bash
      run: |
        set -euo pipefail
        curl -sSL -o helmfile.tar.gz https://github.com/helmfile/helmfile/releases/download/v0.155.0/helmfile_0.155.0_linux_amd64.tar.gz
        mkdir -p hf && tar -xzf helmfile.tar.gz -C hf
        sudo mv hf/helmfile /usr/local/bin/helmfile
        helmfile --version

    - name: Clean old Helm plugins (if any)
      shell: bash
      run: |
        set -euo pipefail
        helm plugin remove secrets || true
        helm plugin remove diff || true
        helm plugin remove s3 || true

    - shell: bash
      run: |
        set -euo pipefail
        HELM="${{ inputs.helm_binary }}"

        if [[ "${{ inputs.uninstall_first }}" == "true" ]]; then
          $HELM plugin remove secrets || true
          $HELM plugin remove diff || true
          $HELM plugin remove s3 || true
        fi

        $HELM plugin install https://github.com/databus23/helm-diff --version "${{ inputs.diff_version }}"
        $HELM plugin install https://github.com/jkroepke/helm-secrets --version "${{ inputs.secrets_version }}"
        $HELM plugin install https://github.com/hypnoglow/helm-s3 --version "${{ inputs.s3_version }}"

        $HELM plugin list
